-- EXERCISE 4 : Aggregation & Business Metrics


-- 14. Display the total number of rentals per customer
-- Tables: customer, rental

SELECT 
    c.customer_id,
    c.first_name,
    c.last_name,
    COUNT(r.rental_id) AS total_rentals
FROM customer AS c
LEFT JOIN rental AS r
    ON c.customer_id = r.customer_id
GROUP BY 
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_rentals DESC;



-- 15. Identify the top 5 customers by total payment amount
-- Tables: payment

SELECT 
    customer_id,
    SUM(amount) AS total_payment
FROM payment
GROUP BY customer_id
ORDER BY total_payment DESC
LIMIT 5;



-- 16. Display total revenue generated by each store
-- Tables: payment, staff, store

SELECT 
    s.store_id,
    SUM(p.amount) AS total_revenue
FROM payment AS p
INNER JOIN staff AS st
    ON p.staff_id = st.staff_id
INNER JOIN store AS s
    ON st.store_id = s.store_id
GROUP BY s.store_id
ORDER BY s.store_id;



-- 17. Display the number of films per category
-- Tables: film_category, category

SELECT 
    c.name AS category_name,
    COUNT(fc.film_id) AS total_films
FROM category AS c
INNER JOIN film_category AS fc
    ON c.category_id = fc.category_id
GROUP BY c.name
ORDER BY total_films DESC;



-- 18. Identify the most rented film
-- Tables: rental, inventory, film

SELECT 
    f.film_id,
    f.title,
    COUNT(r.rental_id) AS total_rentals
FROM rental AS r
INNER JOIN inventory AS i
    ON r.inventory_id = i.inventory_id
INNER JOIN film AS f
    ON i.film_id = f.film_id
GROUP BY 
    f.film_id,
    f.title
ORDER BY total_rentals DESC
LIMIT 1;