services:

  postgres:
    image: postgres:16
    container_name: bookmanagement-db
    environment:
      POSTGRES_DB: BookManagement
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - bookmanagement-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: authorbookmanagement:latest
    container_name: bookmanagement-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: "jdbc:postgresql://postgres:5432/BookManagement"
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      LIBRARIAN_PASSWORD: ${LIBRARIAN_PASSWORD}
    networks:
      - bookmanagement-network

networks:
  bookmanagement-network:
    driver: bridge