pipeline {
    agent any

    stages {

        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Checkout') {
            steps {
                echo 'Code checkout completed'
            }
        }
stage('Build') {
    steps {
        dir('Module5/BookManagement') {
            bat 'mvn clean compile'
        }
    }
}

stage('Test') {
    steps {
        dir('Module5/BookManagement') {
            bat 'mvn test'
        }
    }
}

stage('Package') {
    steps {
        dir('Module5/BookManagement') {
            bat 'mvn clean package'
        }
    }
}

stage('Docker Build') {
    steps {
        dir('Module5/BookManagement') {
            bat 'docker build -t authorbookmanagement:latest .'
        }
    }
}
    post {
        success {
            echo 'BUILD SUCCESS'
        }

        failure {
            echo 'BUILD FAILED'
        }
    }
}